spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://karanpatel7875_db_user:mECP95arVu9ip4Jr@user-data.ukbz5lb.mongodb.net/userdb?appName=user-data
#      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: karan
#    password: karan
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create


server:
  port: 8082
